### CREATE TODO 
POST http://localhost:4004/todoapi/createTodoItem
Content-Type: application/json

{
    "ID":"70700fc0-a16a-454d-a4d6-bebebedde887",
    "name":"THOMAS",
    "completed" : true
}

### UPDATE TODO
POST http://localhost:4004/todoapi/updateTodoItem
Content-Type: application/json

{
    "ID":"70700fc0-a16a-454d-a4d6-bebebedde887",
    "name":"aaaaaaaaaaaaaaaaaa",
    "completed" : false
}

### DELETE TODO
POST  http://localhost:4004/todoapi/deleteTodoItem
Content-Type: application/json

{
    "ID": "70700fc0-a16a-454d-a4d6-bebebedde887"
}

### CREATE LIST
POST http://localhost:4004/todoapi/createTodoList
Content-Type: application/json

{
    "ID":"5474e291-0505-4be0-b2bd-915e7b3c33ff",
    "name":"Todo List"
}

### UPDATE LIST
POST http://localhost:4004/todoapi/updateTodoList
Content-Type: application/json

{
    "ID":"5474e291-0505-4be0-b2bd-915e7b3c33ff",
    "name":"Todos"
}

### DELETE LIST
POST http://localhost:4004/todoapi/deleteTodoList
Content-Type: application/json

{
    "ID":"5474e291-0505-4be0-b2bd-915e7b3c33ff"
}